// File generated by FlutterFire CLI.
// This file will be automatically generated when you run:
//   flutterfire configure
//
// For now, this is a placeholder. You need to:
// 1. Install FlutterFire CLI: dart pub global activate flutterfire_cli
// 2. Run: flutterfire configure
// 3. This file will be automatically generated with your Firebase project configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm9-kIGh0ui6UZ7M5DH-dhweJ-Kiq8hg4',
    appId: '1:586386636592:web:4be4cb2af65c78e74592f5',
    messagingSenderId: '586386636592',
    projectId: 'reach-muslim-leads',
    authDomain: 'reach-muslim-leads.firebaseapp.com',
    storageBucket: 'reach-muslim-leads.firebasestorage.app',
    measurementId: 'G-FER6PQV0PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtStdc-uUhewQ7hmTPwVuMFdSzSdVbXR4',
    appId: '1:586386636592:android:f16b3f846aa31d534592f5',
    messagingSenderId: '586386636592',
    projectId: 'reach-muslim-leads',
    storageBucket: 'reach-muslim-leads.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    iosBundleId: 'com.example.reachmuslim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    iosBundleId: 'com.example.reachmuslim',
  );
}
